baseURL = 'https://syssecfsu.github.io/witty/'

canonifyurls = true
languageCode = 'en-us'
title = 'WiTTY: Web-based interactive TTY'
publishDir = "docs"
enableGitInfo = true


[markup]
[markup.goldmark.renderer]
  unsafe = true
  
[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = true
  BookRepo = 'https://github.com/syssecfsu/witty-docs'
  BookMenuBundle = '/menu'
  BookLogo = 'static/img/logo.svg'
